server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      default-filters:
        - name: GlobalAuthFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: accusation  # 신고관리
          uri: http://localhost:8089
          predicates:
            - Path=/mungta/accusations/**, /mungta/accusation/**, /mungta/admin/accusations/**
        - id: question    # 문의사항
          uri: http://localhost:8080
          predicates:
            - Path=/api/question/**, /api/response/**
#          filters:
#            - RewritePath=/api/question/?(?<segment>.*), /$\{segment}
#            - QuestionAuthFilter
#        - id: store-front
#          uri: http://localhost:8085
#          predicates:
#            - Path=/shop/**, /shop/js/
#        - id: pet-front
#          uri: http://localhost:8084
#          predicates:
#            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"

---

spring:
  profiles: docker
  cloud:
    gateway:
      default-filters:
        - name: GlobalAuthFilter
      routes:
        - id: accusation  # 신고관리
          uri: http://accusation:8080
          predicates:
            - Path=/mungta/accusations/**, /mungta/accusation/**, /mungta/admin/accusations/**
        - id: question    # 문의사항
          uri: http://question:80
          predicates:
            - Path=/api/question/**, /api/response/**
#          filters:
#            - RewritePath=/api/question/?(?<segment>.*), /$\{segment}
#            - QuestionAuthFilter

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
