server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      default-filters:
        - name: GlobalAuthFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: accusation  # 신고관리
          uri: http://localhost:8089
          predicates:
            - Path=/mungta/accusations/**, /mungta/accusation/**, /mungta/admin/accusations/**
        - id: question    # 문의사항
          uri: http://question:8088
          predicates:
            - Path=/api/question/**, /api/response/**
        - id: user        # 사용자관리
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
        - id: notice    # 공지사항
          uri: http://localhost:8090
          predicates:
            - Path=/api/notice/**
        - id: party-management        # 파티관리
          uri: http://localhost:8084
          predicates:
            - Path=/api/party-management/partyInfos/**
#        - id: store-front
#          uri: http://localhost:8085
#          predicates:
#            - Path=/shop/**, /shop/js/
#        - id: pet-front
#          uri: http://localhost:8084
#          predicates:
#            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"

---

spring:
  profiles: docker
  cloud:
    gateway:
      default-filters:
        - name: GlobalAuthFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: accusation  # 신고관리
          uri: http://accusation:8080
          predicates:
            - Path=/mungta/accusations/**, /mungta/accusation/**, /mungta/admin/accusations/**
        - id: question    # 문의사항
          uri: http://question:8080
          predicates:
            - Path=/api/question/**, /api/response/**
        - id: notice    # 공지사항
          uri: http://notice:80
          predicates:
            - Path=/api/notice/**
        - id: user        # 사용자관리
          uri: http://user:8080
          predicates:
            - Path=/api/user/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"

server:
  port: 8080
