server:
  port: 8088
  max-http-header-size: 65536

---

spring:
  profiles:
    activate: local
  cloud:
    gateway:
      default-filters:
        - name: GlobalAuthFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: accusation  # 신고관리
          uri: http://localhost:8089
          predicates:
            - Path=/api/accusation/**
        - id: question    # 문의사항
          uri: http://localhost:8087
          predicates:
            - Path=/api/question/**, /api/response/**
        - id: user        # 사용자관리
          uri: http://localhost:8081
          predicates:
            - Path=/api/user/**
        - id: notice    # 공지사항
          uri: http://localhost:8090
          predicates:
            - Path=/api/notice/**
        - id: party-management        # 파티관리
          uri: http://localhost:8084
          predicates:
            - Path=/api/party-management/partyInfos/**
        - id: party-matching        # 파티매칭
          uri: http://localhost:8085
          predicates:
            - Path=/api/match/**, /api/match/partymembers/**
        - id: review        # 리뷰
          uri: http://localhost:8086
          predicates:
            - Path=/api/review/**
#        - id: store-front
#          uri: http://localhost:8085
#          predicates:
#            - Path=/shop/**, /shop/js/
#        - id: pet-front
#          uri: http://localhost:8084
#          predicates:
#            - Path=/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

