server:
  port: 8080

spring:
  profiles:
    activate: dev
  cloud:
    gateway:
      default-filters:
        - name: GlobalAuthFilter
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: accusation  # 신고관리
          uri: http://accusation:8080
          predicates:
            - Path=/api/accusation/**
        - id: question    # 문의사항
          uri: http://question:8080
          predicates:
            - Path=/api/question/**, /api/response/**
        - id: user        # 사용자관리
          uri: http://user:8080
          predicates:
            - Path=/api/user/**
        - id: notice    # 공지사항
          uri: http://notice:8080
          predicates:
            - Path=/api/notice/**
        - id: party-management        # 파티관리
          uri: http://localhost:8080
          predicates:
            - Path=/api/party-management/partyInfos/**
        - id: matching        # 파티매칭
          uri: http://matching:8080
          predicates:
            - Path=/api/match/**, /api/match/partymembers/**
        - id: review        # 리뷰
          uri: http://review:8080
          predicates:
            - Path=/api/review/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"

management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
          - "health"
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true