apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: mungta
  labels:
    app: gateway
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: gateway
  type: LoadBalancer
